Lmod has detected the following error: The following module(s) are unknown:
"cuda/12.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "cuda/12.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



cuda available with GPU: Tesla V100-SXM2-16GB
[I] Loading dataset OGBG-MOLTOX21...
[I] Finished loading.
[I] Data load time: 2.9203s
MODEL DETAILS:

MODEL/Total parameters: SAN 1051081
[!] -LSPE: Initializing graph positional encoding with rand walk features.
[!] Time taken:  25.154876947402954
[!] -LSPE (For viz later): Adding lapeigvecs to key 'eigvec' for every graph.
[!] Time taken:  4.5299530029296875e-06
[!] Adding full graph connectivity..
Traceback (most recent call last):
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 509, in <module>
    main()
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 504, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "/home/mikemont/final_project/gnn-lspe/main_OGBMOL_graph_classification.py", line 138, in train_val_pipeline
    dataset._make_full_graph() if MODEL_NAME == 'SAN' else dataset._make_full_graph((net_params['p_steps'], net_params['gamma']))
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 233, in _make_full_graph
    self.train = [make_full_graph(graph, adaptive_weighting) for graph in self.train]
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 233, in <listcomp>
    self.train = [make_full_graph(graph, adaptive_weighting) for graph in self.train]
  File "/home/mikemont/final_project/gnn-lspe/data/ogb_mol.py", line 118, in make_full_graph
    eids = full_g.edge_ids(u, v)
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/heterograph.py", line 3267, in edge_ids
    F.as_scalar(F.gather_row(u, idx)),
  File "/home/mikemont/final_project/gnn-lspe/gnn_lspe_env/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py", line 57, in as_scalar
    return data.item()
RuntimeError: a Tensor with 32 elements cannot be converted to Scalar
